# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [2]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [262]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.66208308 0.27237368 0.74363558 ... 0.69035335 0.90192119 0.983587  ]
 [0.14029173 0.31094456 0.94636771 ... 0.89986205 0.43031618 0.14388207]
 [0.59980148 0.48092079 0.59617784 ... 0.11816587 0.64771802 0.10865633]
 ...
 [0.4018133  0.47475667 0.34298551 ... 0.05891757 0.53056584 0.62795494]
 [0.31268398 0.02336667 0.71197752 ... 0.1305382  0.50411389 0.22657299]
 [0.61851889 0.12872586 0.80665859 ... 0.38716039 0.31529358 0.52944732]]
[[0.08926671 0.8641799  0.58255891 ... 0.6390612  0.6512876  0.62347773]
 [0.3033411  0.42764094 0.81280426 ... 0.28631481 0.42227182 0.26922803]
 [0.75663452 0.64082278 0.30304348 ... 0.92150477 0.02415489 0.18230666]
 ...
 [0.08056639 0.69940858 0.48909526 ... 0.33773895 0.79917742 0.34768266]
 [0.86493081 0.64636134 0.23039945 ... 0.81100988 0.22175769 0.73889702]
 [0.55365397 0.52373794 0.91745042 ... 0.65114532 0.23135376 0.23111352]]


.shape это свойство Numpy, которое возвращает кортеж размеров массива.

Без использования numpy

In [263]:
def mult(a, b):
    rows_a = len(a)
    cols_a = len(a[0])
    cols_b = len(b[0])

    c = [[0 for _ in range(cols_b)] for _ in range(rows_a)]

    for i in range(rows_a):
        for j in range(cols_b):
            for k in range(cols_a):
                c[i][j] += a[i][k] * b[k][j]
    return c

C использованием numpy

In [264]:
def np_mult(a, b):
    result = np.matmul(a, b)
    return result

In [265]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)
print(M2)

[[26.09305941 23.68296487 26.49089721 ... 25.67887605 26.46380407
  29.57609552]
 [22.98516041 22.54196997 23.83135829 ... 23.35584828 23.74952363
  24.79791437]
 [26.75371419 25.63891135 29.34335693 ... 27.0255794  27.71513591
  29.74090589]
 ...
 [28.18643321 24.4106983  27.72045118 ... 27.05092124 27.09817222
  28.5300587 ]
 [25.56724306 23.63247201 28.23159883 ... 26.49796893 24.40946597
  30.84548659]
 [28.16902972 23.04349634 28.54517256 ... 27.02746937 26.88622624
  32.45818682]]
CPU times: total: 547 ms
Wall time: 554 ms


In [266]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)
print(M2)

[[30.24072375 28.07261119 26.0315093  ... 27.80039572 24.62490514
  23.79748029]
 [27.42881144 24.309427   21.9095769  ... 23.99148362 22.73193897
  21.86042182]
 [27.36104392 27.90834886 24.81970738 ... 26.01588589 22.89763373
  23.96441249]
 ...
 [28.03239003 25.74984176 23.02374314 ... 24.94792185 22.99981626
  22.1442514 ]
 [27.16512295 26.83487047 23.18087865 ... 25.58083895 23.05568974
  23.93384438]
 [29.41033014 27.83336754 23.75302311 ... 27.59303128 25.01456012
  25.37776229]]
CPU times: total: 0 ns
Wall time: 0 ns


In [267]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.375966007799434e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [268]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.97385359 0.49515957 0.32449997] [0.29724916 0.74040424 0.1433845 ]


In [269]:
def scalar_product(a,b):
    s = sum(i * j for i, j in zip(a, b))
    return s

In [270]:
def np_scalar_product(a,b):
    s = np.dot(a,b)
    return s

In [271]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: total: 0 ns
Wall time: 0 ns
CPU times: total: 0 ns
Wall time: 0 ns


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** Методы numpy написаны на языке C, что позволяет производить операции в тысячи раз быстрее и эффективнее.

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [272]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(matrix):
    diagonal_elements = np.diag(matrix)
    anti_diagonal_elements = np.diag(np.fliplr(matrix))
    diagonal_sum = np.sum(diagonal_elements[diagonal_elements % 2 == 0]) + np.sum(anti_diagonal_elements[anti_diagonal_elements % 2 == 0])
    return diagonal_sum

In [273]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[6, 6, 4, 2, 6],
       [8, 1, 3, 7, 2],
       [3, 3, 1, 2, 4],
       [3, 3, 6, 7, 8],
       [9, 7, 7, 7, 1]])

In [274]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: total: 0 ns
Wall time: 0 ns


12

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [10]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(X):
    row_sums = np.cumsum(X)
    n = np.arange(1, X.shape[0] + 1)
    cumulative_averages = row_sums / n.reshape(1, -1)
    return cumulative_averages

In [41]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)
%time S2 = np_sec_av(A)
print(np_sec_av(A))

[2.44261846e-01 4.85536732e-01 9.23759483e-01 5.49629606e-04
 3.94193235e-01 4.59808712e-01 6.58586554e-01 9.71064063e-01
 3.61871857e-01 5.34750346e-01 2.78068535e-01 1.01071764e-01
 8.80402943e-03 6.36749502e-02 8.96364143e-02 2.24645033e-01
 5.10943633e-01 5.03689593e-01 5.19985688e-01 2.29991797e-01
 5.88375468e-01 6.44148330e-02 8.99944623e-01 7.52687554e-01
 3.03438575e-01 4.16005863e-01 1.12721890e-02 7.63545315e-01
 3.95010989e-01 8.39123793e-02 8.45654301e-01 9.76975579e-01
 9.35167489e-01 5.53617068e-01 8.59915302e-01 8.22967451e-01
 3.24833725e-01 1.96562844e-01 8.66933733e-01 9.33964743e-01
 3.17653523e-01 5.92131350e-01 3.86741857e-04 1.57171570e-01
 7.74375569e-03 4.14856080e-01 3.35929082e-01 9.80915860e-01
 1.74984867e-01 1.91323671e-01 2.36026212e-02 6.34800180e-02
 4.62589579e-01 9.25840045e-01 1.04087144e-01 4.65361279e-01
 1.91675741e-01 3.61918395e-01 6.15896170e-01 2.41566776e-01
 2.88830957e-01 4.35199174e-01 5.50028970e-01 3.73838997e-01
 5.76275130e-01 4.727644

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [38]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    from itertools import groupby
    num = []
    count = []
    for i, j in groupby(a):
        num.append(i)
        count.append(len(list(j)))
    return np.array(num), np.array(count)

In [39]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)
print(np_encode(X))

CPU times: total: 0 ns
Wall time: 0 ns
(array([1, 2, 3, 1, 5, 2, 3]), array([1, 2, 2, 2, 2, 1, 2]))


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [69]:
# функция, решающая задачу с помощью NumPy
from copy import copy
def np_transformation(X, a=1):
    """
    param X: array
    """
    startX = np.copy(X)
    idx = np.arange(len(X))
    mask = idx % 2 == 1
    X = X * mask
    X = X + ~mask * a
    X = X ** (2 * mask + 1)
    X = np.flip(X)
    result = np.concatenate((startX, X))
    return result

In [76]:
X = np.array([i for i in range(1, 100, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)
print(X)
print(np_transformation(X, 5))

CPU times: total: 0 ns
Wall time: 0 ns
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
[     1      3      5      7      9     11     13     15     17     19
     21     23     25     27     29     31     33     35     37     39
     41     43     45     47     49     51     53     55     57     59
     61     63     65     67     69     71     73     75     77     79
     81     83     85     87     89     91     93     95     97     99
 970299      5 857375      5 753571      5 658503      5 571787      5
 493039      5 421875      5 357911      5 300763      5 250047      5
 205379      5 166375      5 132651      5 103823      5  79507      5
  59319      5  42875      5  29791      5  19683      5  12167      5
   6859      5   3375      5   1331      5    343      5     27      5]
